#!/usr/bin/env python3
"""Consolidate per-batch uncertainty answers into one master markdown file.

Usage:
  python consolidate_uncertainty_batches.py [OUT_DIR] [BATCH_COUNT]

Reads OUT_DIR/batches.json (batch_id -> [dossier filenames]) for canonical order,
then for each dossier extracts its '## <filename>: ' block from the matching
batch_NN.md file (NN derived from the batch_id), and writes:

  OUT_DIR/uncertainty_answers.md

with a summary header (resolved / partially-resolved / unresolved counts).

Default OUT_DIR = /home/kostadis/phandalin-output, BATCH_COUNT = 11.
Idempotent: re-running overwrites the master file from the existing batch files.
"""
import os
import re
import sys
import json


def extract_block(text, dossier_file):
    """Extract the dossier block starting at '## <dossier_file>: ' to next '## ' or EOF."""
    pat = re.compile(r"^##\s+" + re.escape(dossier_file) + r"\s*:", re.M)
    m = pat.search(text)
    if not m:
        return None
    start = m.start()
    nxt = re.search(r"\n##\s+", text[start + 2:])
    end = start + 2 + nxt.start() if nxt else len(text)
    return text[start:end].rstrip() + "\n"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "/home/kostadis/phandalin-output"
    nbatches = int(sys.argv[2]) if len(sys.argv) > 2 else 11

    batches_path = os.path.join(out, "batches.json")
    if not os.path.exists(batches_path):
        print(f"ERROR: {batches_path} not found. Run the batch dispatch first.", file=sys.stderr)
        sys.exit(1)
    batches = json.load(open(batches_path, encoding="utf-8"))

    dossier_to_batch = {}
    for bid, files in batches.items():
        for f in files:
            dossier_to_batch[f] = bid

    batch_text = {}
    for n in range(1, nbatches + 1):
        bf = os.path.join(out, f"batch_{n:02d}.md")
        batch_text[n] = open(bf, encoding="utf-8").read() if os.path.exists(bf) else ""

    parts, missing = [], []
    for dossier_file, bid in dossier_to_batch.items():
        n = int(bid.split("_")[1])
        txt = batch_text.get(n, "")
        if not txt:
            missing.append(dossier_file)
            continue
        block = extract_block(txt, dossier_file)
        if block is None:
            missing.append(dossier_file)
            continue
        parts.append(block)

    resolved = sum(1 for p in parts if "Status: [Resolved]" in p)
    partial = sum(1 for p in parts if "Partially resolved" in p)
    unres = sum(1 for p in parts if "Unresolved" in p)

    header = f"""# Campaign Dossier — Uncertainty Resolutions

Generated by mining docs/chapters against the {len(dossier_to_batch)} dossiers
in docs/ensemble/state_dossiers, resolved via subagent batches.

- Resolved: {resolved}
- Partially resolved: {partial}
- Unresolved (could not be answered from chapters): {unres}
- Missing / extraction-failed: {len(missing)}

Each dossier reproduces its '## Uncertainty' questions verbatim (Q:) with a
chapter-grounded resolution (A:). Citations use chN form.

---

"""
    out_path = os.path.join(out, "uncertainty_answers.md")
    open(out_path, "w", encoding="utf-8").write(header + "\n".join(parts))
    print("Wrote", out_path)
    print(f"resolved={resolved} partial={partial} unresolved={unres} missing={len(missing)}")
    if missing:
        print("MISSING:", missing)


if __name__ == "__main__":
    main()
