#!/usr/bin/env python3
"""Apply known wrong-form -> canonical replacements to a VTT transcript.

Reads the corrections glossary, then performs word-boundary replacements
on the transcript and writes the result to ``--output``.

``--output`` is REQUIRED and normally a scratch path, because what this script
produces is a *candidate*, not a deliverable. A session's
``<stem>.transcript.cleaned.vtt`` is generated by CampaignGenerator's
``sd_corrections apply`` from the cue-indexed record
``transcript_corrections.yaml`` (issue #250 R4). Writing that file here would
leave every substitution with no record of itself: ``sd_corrections check``
reports the cues as unexplained, and the next ``apply`` discards the whole
pass. Hand the candidate to ``sd_corrections import`` instead -- see Phase 7 of
SKILL.md. Writing the file a record already claims is refused outright.

Possessive handling: if "Glabbagool" is the canonical and "Lavagul's"
is a wrong-form, the apostrophe form is replaced as written. The script
also auto-fixes the bare possessive form: e.g. if "Lavagul" is a known
wrong-form for "Glabbagool", "Lavagul's" -> "Glabbagool's" is also
applied.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).parent))
from find_unknowns import parse_glossary  # type: ignore

RECORD_NAME = "transcript_corrections.yaml"


def record_owned_output(record_path: Path) -> str | None:
    """Basename of the .cleaned.vtt that ``sd_corrections apply`` owns, or None.

    Read with a regex rather than PyYAML so this stays a stdlib-only script;
    only the two top-level scalars matter, and a record we cannot parse is
    treated as no record at all -- this is a guard, not a validator.
    """
    try:
        text = record_path.read_text(encoding="utf-8")
    except OSError:
        return None
    fields = {}
    for key in ("transcript", "output"):
        m = re.search(rf"^{key}:[ \t]*(\S.*?)[ \t]*$", text, re.MULTILINE)
        if m:
            fields[key] = m.group(1).strip("\"'")
    if fields.get("output"):
        return Path(fields["output"]).name
    raw = fields.get("transcript", "")
    if raw.endswith(".vtt") and not raw.endswith(".cleaned.vtt"):
        return Path(raw[:-4] + ".cleaned.vtt").name
    return None


def word_pattern(literal: str) -> re.Pattern:
    """Compile a boundary-safe, case-insensitive pattern for a wrong-form.

    ``\\b`` asserts a transition between a word char and a non-word char, so a
    wrong-form whose first or last char is punctuation (``L.A.``, ``Glabagul-``)
    can never match its normal context -- ``\\bL\\.A\\.\\b`` needs a WORD char
    after the final period, but real text has a space there. Such rows sit in
    the glossary looking valid and never fire (or worse, only fire glued to the
    next word). Use ``\\b`` for word-char edges and explicit lookarounds for
    punctuation edges; word-char-edged forms behave exactly as before.
    """
    lead = r"\b" if re.match(r"\w", literal[:1]) else r"(?<!\w)"
    tail = r"\b" if re.match(r"\w", literal[-1:]) else r"(?!\w)"
    return re.compile(lead + re.escape(literal) + tail, re.IGNORECASE)


def is_self_matching(wrong: str, right: str) -> bool:
    """True if applying ``wrong -> right`` is not idempotent.

    When the canonical contains the wrong-form as a whole word, the rule fires
    on text that is ALREADY CORRECT and appends the remainder again:

        "Brin -> Brin Bundlewine"  turns  "Brin Bundlewine"
                                   into   "Brin Bundlewine Bundlewine"

    The trigger is a correct transcript, not a mangled one, so the better the
    transcription the more damage the rule does. Such a row is expressing
    "expand a short name to the full name", which a single word-boundary
    substitution cannot do safely -- it has no way to tell an unexpanded
    mention from an already-expanded one. Skip the rule rather than corrupt.
    """
    return word_pattern(wrong).search(right) is not None


def apply(
    text: str, replacements: list[tuple[str, str]]
) -> tuple[str, list[tuple[str, str, int]], list[tuple[str, str]]]:
    """Returns (new_text, [(wrong, right, count), ...], [(wrong, right), ...skipped])."""
    log: list[tuple[str, str, int]] = []
    skipped: list[tuple[str, str]] = []
    # Sort longest-first so multi-word forms replace before subword forms
    for wrong, right in sorted(replacements, key=lambda x: -len(x[0])):
        # Guard: never apply a non-idempotent rule (see is_self_matching).
        if is_self_matching(wrong, right):
            skipped.append((wrong, right))
            continue
        # Case-insensitive match so mid-sentence lowercase forms are caught
        # (VTT transcripts capitalise at sentence start; wrong-forms in the
        # glossary are Title Case but appear lowercase mid-sentence in the VTT)
        new_text, n = word_pattern(wrong).subn(right, text)
        if n:
            log.append((wrong, right, n))
            text = new_text
        # Possessive auto-extension: only if the wrong form doesn't already end in 's
        if not wrong.endswith("'s"):
            new_text, n = word_pattern(wrong + "'s").subn(right + "'s", text)
            if n:
                log.append((wrong + "'s", right + "'s", n))
                text = new_text
    return text, log, skipped


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--vtt", required=True, type=Path)
    ap.add_argument("--glossary", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path,
                    help="Candidate output path. Use a scratch path; the session's "
                         "*.transcript.cleaned.vtt belongs to sd_corrections.")
    args = ap.parse_args()

    out_path = args.output
    # No in-place mode: the raw tape is the archive and is never written.
    if out_path.resolve() == args.vtt.resolve():
        print(f"Error: --output is the input file ({out_path}). The raw transcript is "
              f"the archive and is never overwritten; write a candidate elsewhere.",
              file=sys.stderr)
        return 2
    owned = record_owned_output(out_path.parent / RECORD_NAME)
    if owned and out_path.name == owned:
        print(f"Error: refusing to write {out_path.name} — {out_path.parent}/{RECORD_NAME} "
              f"claims that file, and `sd_corrections apply` regenerates it from the "
              f"record.\n"
              f"  Write a candidate to scratch instead, then record the diff:\n"
              f"    sd_corrections import --dir {out_path.parent} "
              f"--edited <candidate> --record <scratch>/proposed.yaml",
              file=sys.stderr)
        return 2

    vtt_text = args.vtt.read_text(encoding="utf-8")
    replacements, _ = parse_glossary(args.glossary)
    new_text, log, skipped = apply(vtt_text, replacements)

    out_path.write_text(new_text, encoding="utf-8")

    print(f"Wrote {out_path}")
    print(f"Replacements applied:")
    total = 0
    for wrong, right, n in log:
        print(f"  {wrong!r} -> {right!r}: {n}")
        total += n
    print(f"Total: {total}")

    if skipped:
        print(f"\nSKIPPED {len(skipped)} non-idempotent rule(s) "
              f"(canonical contains the wrong-form; would double on correct text):")
        for wrong, right in skipped:
            print(f"  {wrong!r} -> {right!r}")
        print("Run lint_glossary.py for the full report and how to fix these.")

    if total:
        print(f"\nThis is a candidate, not a deliverable. To land it on a session "
              f"tape, record the diff and regenerate:\n"
              f"  sd_corrections import --dir <session-dir> --raw <raw>.transcript.vtt \\\n"
              f"      --edited {out_path} --record <scratch>/proposed.yaml\n"
              f"  # review, merge into <session-dir>/{RECORD_NAME}, then:\n"
              f"  sd_corrections apply --dir <session-dir> && sd_corrections check --dir <session-dir>")
    return 0


if __name__ == "__main__":
    sys.exit(main())
